apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  labels:
    app: events-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-api
      ver: v1.0
  template:
    metadata:
      labels:
        app: events-api
        ver: v1.0
    spec:
      containers:
        - name: events-api
          image: mmanikya/events-api:v1.0
          ports:
            - containerPort: 8082
          env:
            - name: DBHOST
              value: "database-server-mariadb.default"
            - name: DBUSER
              value: "root"
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-server-mariadb
                  key: mariadb-root-password
            - name: DBDATABASE
              value: "events_db"